name: PlateMate CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: Setup LocalStack
        run: |
          docker compose up -d
          # Wait for LocalStack to be ready
          npx wait-on http://localhost:4566/_localstack/health

      - name: Integration Tests
        run: npm run test:integration
        env:
          VITE_API_URL: http://localhost:4566/restapis/local/dev/_user_request_

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: E2E Tests
        run: npm run test:e2e
